### ISSUE TITLE
pk3DS crashes when opening Sun & Moon

### ISSUE THREAD

**Issue by zarkinator01** [kwsch/pk3DS#249]
Steps to reproduce:
1. Open pk3DS
2. Select open from menu and select 'Pokemon Moon' game folder (contains exe and romfs)
3. Exception encountered:
```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.IO.BinaryReader.InternalReadChars(Char[] buffer, Int32 index, Int32 count)
   at System.IO.BinaryReader.ReadChars(Int32 count)
   at pk3DS.Core.CTR.GARC.unpackGARC(Stream stream)
   at pk3DS.Core.CTR.GARC.unpackGARC(Byte[] data)
   at pk3DS.Core.CTR.GARC.MemGARC..ctor(Byte[] data)
   at pk3DS.Core.GameConfig.getMemGARC(String file)
   at pk3DS.Core.GameConfig.getGARCByReference(GARCReference gr)
   at pk3DS.Core.GameConfig.getGARCData(String file, Boolean skipRelative)
   at pk3DS.Core.GameConfig.InitializePersonal()
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Core.GameConfig.Initialize(String romFSpath, String exeFSpath, Int32 lang)
   at pk3DS.Main.openQuick(String path) in C:\Users\zark01\Desktop\aa\pk3DS\Main.cs:line 204
   at pk3DS.Main.B_Open_Click(Object sender, EventArgs e) in C:\Users\zark01\Desktop\aa\pk3DS\Main.cs:line 93
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
pk3DS
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/zark01/Desktop/aa/pk3DS/bin/Debug/pk3DS.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2117.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
pk3DS.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/zark01/Desktop/aa/pk3DS/bin/Debug/pk3DS.Core.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by kwsch** [comment]
Re dump your ROM, whatever garc it is unpacking is corrupt.

**Comment by zarkinator01** [comment]
Didn't work. 
Might it be that my rom is corrupted?
Where would I get a not corrupted one?

**Comment by sora10pls** [comment]
Make sure you're dumping your *own* data, don't go searching the internet for those kinds of files. I'm unable to replicate this with good dumps of Ultra Sun *and* Ultra Moon.
