### ISSUE TITLE
Error when editing

### ISSUE THREAD

**Issue by theoldbucwild** [kwsch/pk3DS#254]
Exception Details:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at pk3DS.Core.CTR.GARC.unpackGARC(Stream stream)
   at pk3DS.Core.CTR.GARC.unpackGARC(Byte[] data)
   at pk3DS.Core.GameConfig.getMemGARC(String file)
   at pk3DS.Core.GameConfig.getGARCByReference(GARCReference gr)
   at pk3DS.Main.<B_Trainer_Click>b__35_0() in C:\BuildAgent\work\b93f10d64d1a1178\pk3DS\Main.cs:line 556
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.205, Culture=neutral, PublicKeyToken=null
C:\Users\Matthew Roehmholdt\Desktop\USUM Randomize Tutorial - Copy\Randomize USUM\HackingToolKit\pk3DS\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Matthew Roehmholdt\Desktop\USUM Randomize Tutorial - Copy\Randomize USUM\HackingToolKit\pk3DS\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

This is what i get when i try to change trainers or static encounters.

**Comment by kwsch** [comment]
https://github.com/kwsch/pk3DS/issues/93

re-dump your ROM

**Comment by theoldbucwild** [comment]
do i redump a rom by doing going into godmode 9 and doing the CXI and NDS file dump?
