### ISSUE TITLE
Issue opening Ultra moon

### ISSUE THREAD

**Issue by Spookenings** [kwsch/pk3DS#311]
Running through visual studio, I am faced with the following error when trying to open the folder containing the Ultra Moon romfs:
```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at pk3DS.Core.GameConfig.getGARCData(String file, Boolean skipRelative) in Y:\Downloads\pk3DS-master\pk3DS.Core\Game\GameConfig.cs:line 176
   at pk3DS.Core.GameConfig.InitializePersonal() in Y:\Downloads\pk3DS-master\pk3DS.Core\Game\GameConfig.cs:line 126
   at pk3DS.Core.GameConfig.InitializeAll() in Y:\Downloads\pk3DS-master\pk3DS.Core\Game\GameConfig.cs:line 118
   at pk3DS.Core.GameConfig.Initialize(String romFSpath, String exeFSpath, Int32 lang) in Y:\Downloads\pk3DS-master\pk3DS.Core\Game\GameConfig.cs:line 114
   at pk3DS.Main.openQuick(String path) in Y:\Downloads\pk3DS-master\pk3DS\Main.cs:line 214
   at pk3DS.Main.B_Open_Click(Object sender, EventArgs e) in Y:\Downloads\pk3DS-master\pk3DS\Main.cs:line 97
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at pk3DS.Program.Main() in Y:\Downloads\pk3DS-master\pk3DS\Program.cs:line 29

```

**Comment by sora10pls** [comment]
Unable to replicate
![image](https://user-images.githubusercontent.com/17801814/38470662-4917bbda-3b34-11e8-9b0c-4ff44a9706c5.png)
