### ISSUE TITLE
Unable to load files

### ISSUE THREAD

**Issue by brokenrevolver** [kwsch/pk3DS#379]
First off, I'm using the 4thgengamer tutorial folder. I've tried dumping two seperate games now, one physical (X) and one digital (Omega Ruby). Worth noting I decrypted X to gm9's out folder instead of copying. Both times I've gotten the same error, where the program says "Data found! Loading persistent data to subforms..." and everything just stays blank. At first, I would not get an error message upon loading the digital game, but now trying to load the physical game I get this message. 

Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at pk3DS.Core.GameConfig.InitializePersonal()
   at pk3DS.Core.GameConfig.InitializeAll()
   at pk3DS.Main.openQuick(String path) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 223
   at pk3DS.Main.B_Open_Click(Object sender, EventArgs e) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 101
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.379, Culture=neutral, PublicKeyToken=null
C:\Users\kjo services\Downloads\3DS Randomizer Pack\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\kjo services\Downloads\3DS Randomizer Pack\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program (albeit with potential side-effects), but please report this error.

**Comment by kwsch** [comment]
pls dont post in multiple locations, I read both.

>3DS Randomizer Pack

I've given multiple responses in the past related to this youtuber's flawed tutorial.
bad ROM dumps (incorrect steps) result in bad data, which causes the program to not behave as intended.
