### ISSUE TITLE
Trainer Editor DOSENT WORK!!! 😬

### ISSUE THREAD

**Issue by HGdesert** [kwsch/pk3DS#416]
Ok so I tryed to open the trainer editor on my rom and it gave my an error. The other things before I give  you the error that got an error are Pick up items,Battle Royal/Tree, and Static Encounters. :(
Heres the error

```
Exception Details:
System.FormatException: Invalid GARC Version: 0x3CCE
   at pk3DS.Core.CTR.GARC.unpackGARC(Stream stream)
   at pk3DS.Core.CTR.GARC.unpackGARC(Byte[] data)
   at pk3DS.Core.GameConfig.GetMemGARC(String file)
   at pk3DS.Core.GameConfig.GetGARCByReference(GARCReference gr)
   at pk3DS.Main.<B_Trainer_Click>b__35_0() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 602
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.
```

**Comment by kwsch** [comment]
Bad ROM dump; not the fault of pk3DS.
