### ISSUE TITLE
Static Encounter "Unhandled Exception"

### ISSUE THREAD

**Issue by MasterBest16** [kwsch/pk3DS#430]
So unfortunately, this happened when I tried to edit the Static Encounters for Omega Ruby and I don't know what to do. Someone please help me. (I was trying to edit the encounter in the Delta Episode with Rayquaza). Help is needed to fix this.

```
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pk3DS.StaticEncounterEditor6.LoadData() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Subforms\Gen6\StaticEncounterEditor6.cs:line 74
   at pk3DS.StaticEncounterEditor6..ctor() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Subforms\Gen6\StaticEncounterEditor6.cs:line 35
   at pk3DS.Main.B_Static_Click(Object sender, EventArgs e) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 1140
```

**Comment by kwsch** [comment]
Without debugging I can't see what exactly is wrong, but the usual suspect is a bad ROM dump.

Line 35 calls RandSettings, not LoadData, and line 74 does File.ReadAllBytes which won't throw that exception; can't trust the stacktrace to be accurate.
https://github.com/kwsch/pk3DS/blob/86c8cb9ba5b6665a8d1a9868508cc855d79e2809/pk3DS/Subforms/Gen6/StaticEncounterEditor6.cs#L74
