### ISSUE TITLE
Unable to randomize TM's, Pickup items, Pokemart, ect. In Omega Ruby

### ISSUE THREAD

**Issue by LucarioRanger** [kwsch/pk3DS#453]
For the love of anything I cannot randomize anything in ExeFS tab in Pk3ds. Whenever I click on any of those things I get an error (below). I have tried everything I can think of but still cannot get it to work. Pictures of what's in the ROM folder in case it is needed. 
This was dumped from a cartridge if that matters

What's in the ROM EXE Folder
![ROMEXE](https://user-images.githubusercontent.com/68386215/87681510-ba952580-c74c-11ea-93e6-f55e5a5f5109.PNG)

What's in the Step 1, EXE folder
![Stp1ExCont](https://user-images.githubusercontent.com/68386215/87681653-e1535c00-c74c-11ea-8065-5f58ca11b196.PNG)

What's in the backup folder
![bckup](https://user-images.githubusercontent.com/68386215/87681745-ffb95780-c74c-11ea-9d0d-369992284b0f.PNG)

The error report
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pk3DS.Core.Util.IndexOfBytes(Byte[] array, Byte[] pattern, Int32 startIndex, Int32 count)
   at pk3DS.TutorEditor6.GetDataOffset(Byte[] data) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Subforms\Gen6\TutorEditor6.cs:line 35
   at pk3DS.TutorEditor6..ctor() in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Subforms\Gen6\TutorEditor6.cs:line 17
   at pk3DS.Main.B_MoveTutor_Click(Object sender, EventArgs e) in C:\BuildAgent\work\ccf72a59f9911202\pk3DS\Main.cs:line 1009
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.402, Culture=neutral, PublicKeyToken=null
C:\Users\bpayne\Desktop\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.exe

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\bpayne\Desktop\3DS Randomizer Pack\Step 2 - Randomize\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program (albeit with potential side-effects), but please report this error.

**Comment by kwsch** [comment]
Bad
ROM
Dump.

There's so many closed issues with this same error message.
