### ISSUE TITLE
Suddn error trying to open Gift Pokémon list for editing

### ISSUE THREAD

**Issue by Eternalityx** [kwsch/pk3DS#475]
Exception Details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pk3DS.GiftEditor6.loadData() in d:\a\1\s\pk3DS\Subforms\Gen6\GiftEditor6.cs:line 89
   at pk3DS.Main.B_Gift_Click(Object sender, EventArgs e) in d:\a\1\s\pk3DS\Main.cs:line 1190
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------------
(removed)
--------------------
User Message:
An unhandled exception has occurred.
You can continue running the program (albeit with potential side-effects), but please report this error.

**Comment by kwsch** [comment]
Bad ROM dump.
