### ISSUE TITLE
Extracting ROM that's been rebuilt once

### ISSUE THREAD

**Issue by Eternalityx** [kwsch/pk3DS#478]
So I'm editing Omega Ruby (JP) rom and I've edited move stats and personal stats for Pokemon, rebuilding the ROM went perfectly fine (Rebuilding it to not lose all my progress if an error occurs) but now trying to extract the .3ds to start editing it again just causes this error to pop up every time, I've tried to make sure no other files are with the rom, to be extracting to an empty folder and nothing seems to help. Idk what the IVFC header is but from what I've seen it just means it never finishes building the second folder that goes with Exefs. If you could help me fix this issue I'd be insanely greatful so I don't need to start again from point zero.

Exception Details:
System.ArgumentException: Bad IVFC Header
   at pk3DS.Core.CTR.RomFS.GetIVFCInfoFromBytes(Byte[] headerBytes)
   at pk3DS.Core.CTR.RomFS.ExtractRomFS(String outputDirectory, RichTextBox TB_Progress, ProgressBar PB_Show)
   at pk3DS.Core.CTR.NCCH.ExtractRomFS(String NCCH_PATH, String outputDirectory, RichTextBox TB_Progress, ProgressBar PB_Show)
   at pk3DS.Core.CTR.NCSD.ExtractFilesFromNCSD(String NCSD_PATH, String outputDirectory, RichTextBox TB_Progress, ProgressBar PB_Show)
   at pk3DS.Main.<>c__DisplayClass23_0.<extractNCSD>b__0() in d:\a\1\s\pk3DS\Main.cs:line 327
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by kwsch** [comment]
Have you tried extracting it with another tool?

**Comment by Eternalityx** [comment]
> Have you tried extracting it with another tool?

I tried using .NET 3ds Toolkit to extract the rom but it's been stuck at "Extracting as decrypted CCI..." for about 6 hours so I think that's a no for working. It has successfully extracted: ExHeader.bin, HeaderNCCH.bin, HearNCCH0.bin, LogoLZ.bin and PlainRGN.bin. I will try another program tomorrow to extract it again.

**Comment by kwsch** [comment]
If the ROM cannot be unpacked by any other tool, then it's not an issue with pk3DS, unfortunately.
