### ISSUE TITLE
Error when trying to launch

### ISSUE THREAD

**Issue by YouOneUnderscore** [kwsch/pk3DS#539]
I'm editing a rom of pokemon Omega ruby and running it on citra, I tried to open it again after not using it for a few days and it told me that the game text file was corrupt and to change the current one for the backup so I did that, tried to launch it again and now I get a different error.
It doesn't say anything this time just gives me this:
Exception Details:
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at pk3DS.RandSettings.Load(String[] lines) in D:\a\1\s\pk3DS\Tools\RandSettings.cs:line 24
   at pk3DS.Main..ctor() in D:\a\1\s\pk3DS\Main.cs:line 73
   at pk3DS.Program.Main() in D:\a\1\s\pk3DS\Program.cs:line 32

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

pk3DS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\hammy\OneDrive\Desktop\pk3DS\pk3DS.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

pk3DS.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\hammy\OneDrive\Desktop\pk3DS\pk3DS.Core.dll

--------------------
User Message:
An unhandled exception has occurred.
The program must now close.

No idea what is going on with this it still runs on the emulator but I can't edit it anymore which really sucks.
Any insight would be great thanks.

**Comment by kwsch** [comment]
Delete the rand config files that are next to the exe
